plugin_repo(
  name = "go",
  revision = "v1.7.4",
  plugin = "go-rules",
  owner = "please-build",
)

plugin_repo(
  name = "proto",
  revision = "v0.2.1",
  plugin = "proto-rules",
  owner = "please-build",
)

plugin_repo(
  name = "go_proto",
  revision = "v0.2.0",
  plugin = "go-proto-rules",
  owner = "please-build",
)
