plugin_repo(
    name = "proto",
    owner = "please-build",
    revision = "v0.4.0",
)

plugin_repo(
    name = "go",
    owner = "please-build",
    revision = "v1.22.0",
)

plugin_repo(
    name = "go-proto",
    owner = "please-build",
    revision = "v0.3.0",
)
